<a href="https://colab.research.google.com/github/2303A51589/pythonDS/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
l=[10,20,30,40]
print(l)
if 20 in l:
  print("found")
l.append(50)
print(l)
l.remove(30)
print(l)
l.insert(2,25)
print(l)
l.pop()
print(l)
l.sort()
l.reverse()
print(l)
print(sum(l))


print(min(l))
student=[[20,30],[50,60],[23,45],[76,87]]
print(student)

import numpy as np

student = np.array(student)
print("\nStudent:")
print(student)



[10, 20, 30, 40]
found
[10, 20, 30, 40, 50]
[10, 20, 40, 50]
[10, 20, 25, 40, 50]
[10, 20, 25, 40]
[40, 25, 20, 10]
95
10
[[20, 30], [50, 60], [23, 45], [76, 87]]

Student:
[[20 30]
 [50 60]
 [23 45]
 [76 87]]


In [2]:
t = (10,3,24,25,26)

print(t)

t = (10,3,24,25,24,26)
print(t)
for i in t :
  print(type(i),i)
if 20 in t:
  print("found")
else:
  print("not found")
t = (10,3,24,25,24,26)
print(t.count(25))
print(t.index(24))
l = [10,20,30,40,]
mytuple = tuple(l)
print(mytuple)
student = ((20,30),(34,45),(67,78))
print(student)

(10, 3, 24, 25, 26)
(10, 3, 24, 25, 24, 26)
<class 'int'> 10
<class 'int'> 3
<class 'int'> 24
<class 'int'> 25
<class 'int'> 24
<class 'int'> 26
not found
1
2
(10, 20, 30, 40)
((20, 30), (34, 45), (67, 78))


In [3]:



student={"name":"python","id":"101","branch":"cse"}
print(student.keys())
print(student.values())
print(student.items())
print(student["name"])

dict_keys(['name', 'id', 'branch'])
dict_values(['python', '101', 'cse'])
dict_items([('name', 'python'), ('id', '101'), ('branch', 'cse')])
python


In [6]:
l = [[10,20],[30,40],[70,39]]
for i in l:
  print(i)

[10, 20]
[30, 40]
[70, 39]


In [18]:
s = {1,2,3,4,6}
print(s)
s = {1,2,3,2,3,2}
print(s)
for i in s:
  print(i)
if 2 in s:
  print("dhorikindhi")
else:
  print("dorakale")
s = {1,12,13}
print(sum(s))
s.add(4)
print(s)
s = {1,2,3,4,6}
s.remove(2)
print(s)
s.clear()
print(s)

{1, 2, 3, 4, 6}
{1, 2, 3}
1
2
3
dhorikindhi
26
{1, 4, 12, 13}
{1, 3, 4, 6}
set()


In [19]:

student = np.array([
    [78, 85, 90],
    [92, 76, 88],
    [65, 70, 75],
    [88, 91, 85],
    [70, 65, 72]
])

print("Student:")
print(student)
average_marks = np.mean(student)
min_marks = np.min(student)
max_marks = np.max(student)



Student:
[[78 85 90]
 [92 76 88]
 [65 70 75]
 [88 91 85]
 [70 65 72]]


In [20]:
frst_three = student[:3]
print(frst_three)

[[78 85 90]
 [92 76 88]
 [65 70 75]]


In [23]:
print_marks_index_4 = student[4,:]
print(print_marks_index_4)

[70 65 72]


In [25]:
import numpy as np
students_above_80 = student[np.any(student > 80, axis=1)]
print("Marks of students who scored above 80 in at least one subject:")
print(students_above_80)

Marks of students who scored above 80 in at least one subject:
[[78 85 90]
 [92 76 88]
 [88 91 85]]


In [27]:
subject_wise_performance = student.T
print("Subject-wise performance (transposed array):")
print(subject_wise_performance)

Subject-wise performance (transposed array):
[[78 92 65 88 70]
 [85 76 70 91 65]
 [90 88 75 85 72]]
