<a href="https://colab.research.google.com/github/2303A51589/pythonDS/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
fp = open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("this is file handling in python.\n")
fp.write("sr university.\n")
fp.write("koushik")
fp.close()

In [10]:
file = open("example.txt","r")
print(file.read())
file.close()

Hello,B.Tech students!
this is file handling in python.
sr university.
koushik


In [16]:
file = open("example.txt","r")
line1 =file.readline()
print(line1)
line2 =file.readline()
print(line2)
line3 =file.readline()
print(line3)

file.close()

Hello,B.Tech students!

this is file handling in python.

sr university.



In [17]:
file = open("example.txt","r")
lines =file.readlines()
print(lines)
file.close()

['Hello,B.Tech students!\n', 'this is file handling in python.\n', 'sr universitykoushik']


In [38]:
# Appending data to an existing file
file = open("example.txt","a")
file.write("This is appended text.\n")
file.close()

In [39]:
file = open("example.txt","r")
print(file.read())
file.close()

Hello,B.Tech students!
this is file handling in python.
sr universitykoushikThis is appended text.
This is appended text.
This is appended text.
This is appended text.
This is appended text.
This is appended text.



In [40]:
import csv
with open("data.csv","w",newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["John",25,"New York"])
    writer.writerow(["Alice",30,"London"])
    writer.writerow(["Bob",28,"Paris"])


In [41]:
#reading from csv
with open("data.csv","r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['John', '25', 'New York']
['Alice', '30', 'London']
['Bob', '28', 'Paris']


In [43]:
import numpy as np
arr1 =np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [45]:
arr2= np.array([[1,2,3,4],[6,7,8,9]])
print(arr2)

[[1 2 3 4]
 [6 7 8 9]]


In [46]:
zero_arr = np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
ones_arr = np.ones((3,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
range_arr = np.arange(1,50,6)
print(range_arr)

[ 1  7 13 19 25 31 37 43 49]


In [52]:
rand_arr= np.random.rand(3,3)
print(rand_arr)

[[0.24949368 0.33856596 0.60238942]
 [0.45588624 0.3995846  0.71856443]
 [0.1349784  0.49544945 0.24444755]]


In [59]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)

(2, 3)
int64
6
2
8


In [60]:
#array operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [62]:
array = np.array([[1,2,3],[4,5,6]])
print(np.sum(array))
print(np.sum(array,axis=0))
print(np.sum(array,axis=1))
print(np.min(array))
print(np.max(array))



21
[5 7 9]
[ 6 15]
1
6


In [63]:
#broadcasting
a = np.array([1,2,3])
b =5
print(a+b)
c = np.array([[1,2,3],[1,2,3]])
d = np.array([4,5,6])
print(c+d)

[6 7 8]
[[5 7 9]
 [5 7 9]]
